In [1]:
import glob
import pandas as pd

In [4]:
paths = glob.glob('df_new/*.*')

In [12]:
paths

['df_new/df_new2.csv',
 'df_new/df_new3.csv',
 'df_new/df_new1.csv',
 'df_new/df_new4.csv',
 'df_new/df_new5.csv',
 'df_new/df_new7.csv',
 'df_new/df_new6.csv',
 'df_new/df_new8.csv']

In [111]:
df2 = pd.read_csv(paths[0])
df3 = pd.read_csv(paths[1])
df1 = pd.read_csv(paths[2])
df4 = pd.read_csv(paths[3])
df5 = pd.read_csv(paths[4])
df7 = pd.read_csv(paths[5])
df6 = pd.read_csv(paths[6])
df8 = pd.read_csv(paths[7])

In [112]:
len(df1), len(df2), len(df3), len(df4), len(df5), len(df6), len(df7), len(df8)

(4100, 4100, 4100, 4100, 4100, 4100, 4100, 2005)

In [113]:
df = pd.concat([df3, df4, df5, df6, df7, df8], axis = 0)

In [114]:
df = df.reset_index(drop=True)

In [115]:
df = df.drop('Unnamed: 0', axis = 1)

In [116]:
df.to_csv('beforejoin.csv', index = False, encoding = 'utf-8')

In [117]:
df

,start,end,startlat,startlng,endlat,endlng,direction,distance,duration,taxiFare
0,성산제1동,일원1동,126.907850,37.563408,127.087963,37.491839,성산제1동일원1동,26610,2963.951,22400
1,반포4동,일원1동,127.000385,37.497431,127.087963,37.491839,반포4동일원1동,11186,1950.518,12000
2,월계3동,일원1동,127.069249,37.621048,127.087963,37.491839,월계3동일원1동,22588,1719.547,19300
3,압구정동,일원1동,127.030713,37.530642,127.087963,37.491839,압구정동일원1동,9712,1687.149,10100
4,삼양동,일원1동,127.019773,37.625052,127.087963,37.491839,삼양동일원1동,23020,2242.687,20600
...,...,...,...,...,...,...,...,...,...,...
22500,방화제1동,신흥1동,126.817026,37.570366,127.141172,37.443038,방화제1동신흥1동,44202,4121.124,37650
22501,길음제2동,신흥1동,127.027316,37.606665,127.141172,37.443038,길음제2동신흥1동,31666,2749.867,27710
22502,행운동,신갈동,126.957046,37.480654,127.107056,37.272653,행운동신갈동,36013,3038.712,33310
22503,인수동,서현2동,127.010631,37.641511,127.134599,37.376037,인수동서현2동,39658,3772.508,36090
22504,도곡1동,서현2동,127.039025,37.488238,127.134599,37.376037,도곡1동서현2동,18916,2215.335,20290

In [118]:
df = df.drop(['start', 'end', 'startlat', 'startlng', 'endlat', 'endlng'], axis= 1)

In [119]:
df

       direction  distance  duration  taxiFare
0      성산제1동일원1동     26610  2963.951     22400
1       반포4동일원1동     11186  1950.518     12000
2       월계3동일원1동     22588  1719.547     19300
3       압구정동일원1동      9712  1687.149     10100
4        삼양동일원1동     23020  2242.687     20600
...          ...       ...       ...       ...
22500  방화제1동신흥1동     44202  4121.124     37650
22501  길음제2동신흥1동     31666  2749.867     27710
22502     행운동신갈동     36013  3038.712     33310
22503    인수동서현2동     39658  3772.508     36090
22504   도곡1동서현2동     18916  2215.335     20290

[22505 rows x 4 columns]

In [120]:
path = glob.glob('master_cleansing_done.csv')
df_origin = pd.read_csv(path[0])

In [121]:
df_origin

,no,cartype,예정시간,배차시간,승차시간,startpos1,startpos2,slat,slng,endpos1,endpos2,elat,elng
0,7658,중형승합,2018-01-23 00:04:00,2018-01-23 00:18:42,2018-01-23 00:34:08,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808
1,7909,중형승합,2019-07-23 07:00:00,2019-07-23 07:56:33,2019-07-23 08:21:30,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808
2,4174,중형승합,2021-08-27 07:00:00,2021-08-27 07:00:27,2021-08-27 07:20:23,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808
3,8040,중형승합,2021-08-12 07:00:00,2021-08-12 07:09:31,2021-08-12 07:18:53,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808
4,8279,중형승합,2022-03-02 07:22:00,2022-03-02 07:27:35,2022-03-02 07:55:29,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389145,3600,중형승합,2020-12-25 08:07:00,2020-12-25 08:08:26,2020-12-25 09:29:43,성북구,길음제2동,127.027316,37.606665,수정구,신흥1동,127.141172,37.443038
389146,4964,중형승합,2021-05-16 09:14:03,2021-05-16 09:22:04,2021-05-16 09:54:56,성북구,길음제2동,127.027316,37.606665,수정구,신흥1동,127.141172,37.443038
389147,1192,중형승합,2018-09-25 08:36:00,2018-09-25 08:41:28,2018-09-25 09:12:20,관악구,행운동,126.957046,37.480654,기흥구,신갈동,127.107056,37.272653
389148,1556,중형승합,2018-06-16 07:00:00,2018-06-16 07:07:27,2018-06-16 07:32:12,강북구,인수동,127.010631,37.641511,분당구,서현2동,127.134599,37.376037
389149,8064,중형승합,2020-09-06 09:31:00,2020-09-06 09:39:44,2020-09-06 10:46:26,강남구,도곡1동,127.039025,37.488238,분당구,서현2동,127.134599,37.376037

In [122]:
df_origin['direction'] = df_origin['startpos2'] + df_origin['endpos2']

In [123]:
df_origin

,no,cartype,예정시간,배차시간,승차시간,startpos1,startpos2,slat,slng,endpos1,endpos2,elat,elng,direction
0,7658,중형승합,2018-01-23 00:04:00,2018-01-23 00:18:42,2018-01-23 00:34:08,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
1,7909,중형승합,2019-07-23 07:00:00,2019-07-23 07:56:33,2019-07-23 08:21:30,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
2,4174,중형승합,2021-08-27 07:00:00,2021-08-27 07:00:27,2021-08-27 07:20:23,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
3,8040,중형승합,2021-08-12 07:00:00,2021-08-12 07:09:31,2021-08-12 07:18:53,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
4,8279,중형승합,2022-03-02 07:22:00,2022-03-02 07:27:35,2022-03-02 07:55:29,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389145,3600,중형승합,2020-12-25 08:07:00,2020-12-25 08:08:26,2020-12-25 09:29:43,성북구,길음제2동,127.027316,37.606665,수정구,신흥1동,127.141172,37.443038,길음제2동신흥1동
389146,4964,중형승합,2021-05-16 09:14:03,2021-05-16 09:22:04,2021-05-16 09:54:56,성북구,길음제2동,127.027316,37.606665,수정구,신흥1동,127.141172,37.443038,길음제2동신흥1동
389147,1192,중형승합,2018-09-25 08:36:00,2018-09-25 08:41:28,2018-09-25 09:12:20,관악구,행운동,126.957046,37.480654,기흥구,신갈동,127.107056,37.272653,행운동신갈동
389148,1556,중형승합,2018-06-16 07:00:00,2018-06-16 07:07:27,2018-06-16 07:32:12,강북구,인수동,127.010631,37.641511,분당구,서현2동,127.134599,37.376037,인수동서현2동
389149,8064,중형승합,2020-09-06 09:31:00,2020-09-06 09:39:44,2020-09-06 10:46:26,강남구,도곡1동,127.039025,37.488238,분당구,서현2동,127.134599,37.376037,도곡1동서현2동

In [124]:
df_origin

,no,cartype,예정시간,배차시간,승차시간,startpos1,startpos2,slat,slng,endpos1,endpos2,elat,elng,direction
0,7658,중형승합,2018-01-23 00:04:00,2018-01-23 00:18:42,2018-01-23 00:34:08,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
1,7909,중형승합,2019-07-23 07:00:00,2019-07-23 07:56:33,2019-07-23 08:21:30,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
2,4174,중형승합,2021-08-27 07:00:00,2021-08-27 07:00:27,2021-08-27 07:20:23,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
3,8040,중형승합,2021-08-12 07:00:00,2021-08-12 07:09:31,2021-08-12 07:18:53,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
4,8279,중형승합,2022-03-02 07:22:00,2022-03-02 07:27:35,2022-03-02 07:55:29,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389145,3600,중형승합,2020-12-25 08:07:00,2020-12-25 08:08:26,2020-12-25 09:29:43,성북구,길음제2동,127.027316,37.606665,수정구,신흥1동,127.141172,37.443038,길음제2동신흥1동
389146,4964,중형승합,2021-05-16 09:14:03,2021-05-16 09:22:04,2021-05-16 09:54:56,성북구,길음제2동,127.027316,37.606665,수정구,신흥1동,127.141172,37.443038,길음제2동신흥1동
389147,1192,중형승합,2018-09-25 08:36:00,2018-09-25 08:41:28,2018-09-25 09:12:20,관악구,행운동,126.957046,37.480654,기흥구,신갈동,127.107056,37.272653,행운동신갈동
389148,1556,중형승합,2018-06-16 07:00:00,2018-06-16 07:07:27,2018-06-16 07:32:12,강북구,인수동,127.010631,37.641511,분당구,서현2동,127.134599,37.376037,인수동서현2동
389149,8064,중형승합,2020-09-06 09:31:00,2020-09-06 09:39:44,2020-09-06 10:46:26,강남구,도곡1동,127.039025,37.488238,분당구,서현2동,127.134599,37.376037,도곡1동서현2동

In [104]:
df_origin.merge(df, on = 'direction', how = 'outer')

,no,cartype,예정시간,배차시간,승차시간,startpos1,startpos2,slat,slng,endpos1,endpos2,elat,elng,direction,distance,duration,taxiFare
0,7658,중형승합,2018-01-23 00:04:00,2018-01-23 00:18:42,2018-01-23 00:34:08,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동,NaN,NaN,NaN
1,7909,중형승합,2019-07-23 07:00:00,2019-07-23 07:56:33,2019-07-23 08:21:30,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동,NaN,NaN,NaN
2,4174,중형승합,2021-08-27 07:00:00,2021-08-27 07:00:27,2021-08-27 07:20:23,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동,NaN,NaN,NaN
3,8040,중형승합,2021-08-12 07:00:00,2021-08-12 07:09:31,2021-08-12 07:18:53,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동,NaN,NaN,NaN
4,8279,중형승합,2022-03-02 07:22:00,2022-03-02 07:27:35,2022-03-02 07:55:29,성북구,장위제1동,127.043713,37.614125,동대문구,회기동,127.055313,37.590808,장위제1동회기동,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389145,3600,중형승합,2020-12-25 08:07:00,2020-12-25 08:08:26,2020-12-25 09:29:43,성북구,길음제2동,127.027316,37.606665,수정구,신흥1동,127.141172,37.443038,길음제2동신흥1동,31666.0,2749.867,27710.0
389146,4964,중형승합,2021-05-16 09:14:03,2021-05-16 09:22:04,2021-05-16 09:54:56,성북구,길음제2동,127.027316,37.606665,수정구,신흥1동,127.141172,37.443038,길음제2동신흥1동,31666.0,2749.867,27710.0
389147,1192,중형승합,2018-09-25 08:36:00,2018-09-25 08:41:28,2018-09-25 09:12:20,관악구,행운동,126.957046,37.480654,기흥구,신갈동,127.107056,37.272653,행운동신갈동,36013.0,3038.712,33310.0
389148,1556,중형승합,2018-06-16 07:00:00,2018-06-16 07:07:27,2018-06-16 07:32:12,강북구,인수동,127.010631,37.641511,분당구,서현2동,127.134599,37.376037,인수동서현2동,39658.0,3772.508,36090.0
389149,8064,중형승합,2020-09-06 09:31:00,2020-09-06 09:39:44,2020-09-06 10:46:26,강남구,도곡1동,127.039025,37.488238,분당구,서현2동,127.134599,37.376037,도곡1동서현2동,18916.0,2215.335,20290.0