# 라이브러리 설치

In [13]:
! pip install pandas_datareader

Collecting pandas_datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
     |████████████████████████████████| 109 kB 1.4 MB/s eta 0:00:01
Requirement already satisfied: requests>=2.19.0 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from pandas_datareader) (2.27.1)
Requirement already satisfied: lxml in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from pandas_datareader) (4.6.3)
Requirement already satisfied: pandas>=0.23 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from pandas_datareader) (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.23->pandas_datareader) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.23->pandas_datareader) (1.23.0)
Requirement already satisfied: six>=1.5 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas_datareader) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.19.0->pandas_datareader) (2022.5.18.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.19.0->pandas_datareader) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.19.0->pandas_datareader) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/jeon-eunji/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.19.0->pandas_datareader) (3.3)
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.10.0

In [15]:
import glob
import pandas as pd
import pandas_datareader.data as web
import matplotlib.pyplot as plt
%matplotlib inline
from datetime import datetime
import plotly.graph_objs as go
import plotly.offline as py

In [26]:
import fbprophet

ModuleNotFoundError: No module named 'fbprophet'

In [21]:
glob.glob('master_final_220706.csv')

['master_final_220706.csv']

In [24]:
df = pd.read_csv('master_final_220706.csv')
df.drop('Unnamed: 0', axis =1)

,cartype,예정시간,배차시간,승차시간,startpos1,startpos2,endpos1,endpos2,start_lat,start_lng,end_lat,end_lng,direction,distance,duration,taxiFare
0,중형승합,2018-01-23 00:04:00,2018-01-23 00:18:42,2018-01-23 00:34:08,성북구,장위제1동,동대문구,회기동,127.043713,37.614125,127.055313,37.590808,장위제1동회기동,4289,648.464,5600
1,중형승합,2018-01-23 00:17:00,2018-01-23 00:50:37,2018-01-23 01:19:22,중랑구,면목제7동,노원구,상계1동,127.086985,37.578995,127.054978,37.679901,면목제7동상계1동,14493,1318.675,13700
2,중형승합,2018-01-23 00:30:00,2018-01-23 00:17:06,2018-01-23 00:17:39,성북구,정릉제3동,강북구,수유제3동,127.004186,37.608958,127.023125,37.638715,정릉제3동수유제3동,4869,864.161,6200
3,중형승합,2018-01-23 00:47:00,2018-01-23 00:51:19,2018-01-23 01:09:33,구로구,고척제2동,관악구,은천동,126.858712,37.506706,126.942428,37.485309,고척제2동은천동,10247,1652.785,11000
4,중형승합,2018-01-23 01:08:00,2018-01-23 01:44:17,2018-01-23 02:06:53,동대문구,회기동,성북구,장위제2동,127.055313,37.590808,127.054521,37.612390,회기동장위제2동,3778,598.639,5200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407548,대형승용,2022-06-24 07:00:00,2022-06-24 07:12:38,2022-06-24 07:55:24,성북구,돈암제2동,강남구,대치4동,127.010566,37.598039,127.057913,37.499741,돈암제2동대치4동,15572,3581.405,18900
407549,중형승합,2022-06-24 07:00:00,2022-06-24 07:09:10,2022-06-24 07:25:35,은평구,구산동,은평구,구산동,126.910389,37.611745,126.910389,37.611745,구산동구산동,1000,240.000,0
407550,중형승합,2022-06-24 07:00:00,2022-06-24 07:04:27,2022-06-24 07:25:35,노원구,상계8동,영등포구,영등포동,127.051587,37.666785,126.910692,37.520398,상계8동영등포동,47328,2667.002,45030
407551,중형승합,2022-06-24 07:00:00,2022-06-24 08:06:22,2022-06-24 06:55:01,성북구,길음제1동,강북구,번제1동,127.019392,37.610486,127.028847,37.637891,길음제1동번제1동,4631,772.956,6200
407552,중형승합,2022-06-24 07:00:00,2022-06-24 07:05:08,2022-06-24 08:31:07,강동구,천호제2동,강동구,명일제1동,127.125435,37.543526,127.144366,37.551245,천호제2동명일제1동,3075,459.402,4600